language: node_js
node_js: lts/carbon
services:
  - docker
addons:
  apt:
    packages:
      - libsecret-1-0
script:
  - chmod +x ./scripts/docker-deploy.sh
deploy:
  - provider: npm
    api_key:
      secure: JRbHO/Uy6/WVvysJ6XtSrErVHSpf7ha2yh684qFTDVKesom+hs9yH+OsNjuoUky9spm3J6Pt2oCBlTcLOWEWV5xih1zW7nYJisd4W03yp0hGeNMopVGd2qT1sHw6BynaV9pV/loOW42TpsGp5f/giuOqYn/J3s9yX03VkypTecdDintIYgiYIcGfFrTQO6KRIsL7uhwATAy64OjQTLQMC5Otz9aREOdpwgIeVlcoq9r/sBKVgnXAY6crqzW+rwmiEzvZmzn9BGMZ0EWSmgVCtb6/DYr3SQSD0G5QNBpawC5zR/BjovHJXwszhaNozAFSQmNr5AarKFdC+YonLVioaR+aPsTJjmhpzDu65wm5oTZBaeLMhhY2qCw3p/dHWo5W9D3adTMvI2W0/fdbOSwCCzjpzC6Vai3WEFMV9ZGiEmtA7C+gLgUrwN0orAjFyQmQRjgUi5OKb+F+zYpq8XvP4M6tOeTsuvkEBO2voFn+10BeOItfjVzoEvDMW/Yy8ybisjo1ceLj1BYYePJZcAeg8TheXOiNeqYms9HiZ7TEPBL9lxWjqqekNryeLB5P/4C8k9AJe/fY7VBN3KxFyzDPRaTXR8VR+tukBIT794U7iUuxwn9Onx+eW6/WoghvkrjTcQ6EyXxMOI7b72IJ40tEIl5Rpc3D1cBUcsBoeDgmqJE=
    on:
      tags: true
      repo: collinewait/ttcat
    email:
      secure: EOEi2GG+XrIeUagQ2VaYFsyTm+mmPM+H8hx6YvTySQHhYq795AIoxea9OXrRYtPu34vcEhEJbg2Rcq1D1veJpVWGGg49Bk6dr4iyxEnThPk82bhbIlICHXNLhJunbNF3SF7mpHaw9Mv1jyI/Z1GqmsHTmxrrLysjgc1IkOMVB3nGEhVHhKHZ/eo0kUVZ0iBDIVAmy4+9mPL18xty74QMnEooEH6oEtb3d47lZ6ttYHEsyx2gvmf+HXPgpN4qUSOYdqfk8ktPHRw+HqdVJVun80kevm5q4ISw9ZxA1lC8ShxiBdku/TzjPibELi9EKvGF4BPrVEzK4T/lf53k4w5Phjwd8OZ0aEILYORNQTbcK6zwZFHdrrQjXkdwYMHb+Z5gUqOBhNc9q+19Z5uuokCZdm9xXq1faV8DYWkZsCT4oxRDoVaaOI9WWbNEheNiXLQ5n51SQvUw7WTsOOY2WfaK5iVPrNVx92LkYeuuC2A3uN9EORHCtsuJfeJQgE4mlXls7t/M2OUhiZPBA1wLCQYZDsLbcna+k/zsoEJkTJNV5pJuFwXtCUnNW74F7fz4EH2Fpm5BKVm0YeAJv18PfOxOpPT6VKpQS2SCsAwhvJKeg4S7EgLHkjzWI/3OnmqrXnt5I4sn51ef/fLnCWLAmvSOviyKL5G8OpTfFRbdX6hj4Kw=
  - provider: script
    script: bash ./scripts/docker-deploy.sh
    skip_cleanup: true
    on:
      tags: true
      repo: collinewait/ttcat
env:
  global:
    - secure: N9devQFtY+Urm23XngflUwIQdI7I2TgW6rxVntCfo+Suo1TbwzlmQwEQOkgLDgvAd3qY4duIsFYVlwPeCROteTSUufqHT1qUxq8ObxK9oLYBygxZXwew9ztDxbTUs1XQ+npujDwWmD7Iav/2oF7xLHZczjzi4wjp4m+XsCb8MjsavUtChJAswsOQBTCHd4ivRe+rRoO8VSwuh4PliP3GEt7LrX/fy0QPtpT39Puh7oQ5fbBAEvAqgQmAap0xRxV2B7B7DYKnkTMi1ADh6bNtlW44iahiILAUsbpKsRo2AUvfkIzjni3p6bcpXFAo1Y/6WkFNeJw6zyvgiU6WMb4KRO6f0Wolz0VeSejxljURYS95aETyqCEb4dJtC8/NGdw9zEC29QoLINfOwDCcquT+RDM9/nRChyCHkrnlYPX/T3CCUitrEZ6vqY57F/ltD/GB627VbHqzKdSN0pq49yyb1ICcHSAc681xcql6XrAp4b6IplhfrEfhqgGDWAqk4vpvwmwRrVQvSd6+XhEc4ia9vWSRfEA+yHy6h11PODHCxrPkc7m7omKO+l7qCXURjlR62WA4eFrKqfxym3gujHSLBZHfU57n8hGWbKG3MUTWeryOrtPaWwpamsHbJW9Krc5nHP3xQXWSuRpHDZ5OEm7Og1D01nB1GRiDMF9qZIC4+5I=
    - secure: b1OiX+CR8WfAINzYMjOuU1mUIDQbzPYSwKy1/sxufzckznml+jaHfDB1AIaVcNY5S1TVaWGGRuToPA/RywZy4IpGyDRXjmF1CVr3ou8NATe0mxoYSQuzkwuWEuhb3lEbBdyVzIbilgUWJo637eIq2bFsqmUuRdWi9yCa/pRhFvf3DLQHeb03T0lypaIgySej6YJ80ROXOA/SHt1mtAINF9D93lnCpieeIKEEB4Z5VyYzpQGXAuloA5qjpafnmu5MvemCgzZvjWDavhumrQZcHq4iVOH6qp9bVn3uT+OXzOwBF53mRvS9A50Uv7EBY77ZSDl11QbEcXRq+vNQriEKcXOPzQ+Vif35hRKY+/dhkpNsI2kHnYWOwlPg47YfRy0NmZv9SDF0tCzoXTO76QuPWDwed0aj41LiWgUXZBE4rzotw9aSaAvLIxZSqkvoc1442j7B1fsFn2s8RK/88lBQEV+rRc+MHNJZMmmW9Km1NvyjRvCzPFjOAAA/y28K1+NRUwnt6wmdNzK97xGFEtjNPtK3M63KEaSaC16gr7kWV07616YU/tvE9tPErOX/QQC+AqCmuDH7P2EX9Xqez74Jl/fPtTrZ+ccsg6Rs2E/7Ed1VNfTxt9EZLIb5zKhqTtTVIJWL2osPaIQpa4jImE5k/WzTruXD4WGaPUsunfmP1iU=
